### ISSUE TITLE
Docker Hub don't deliver the latest version of Matomo (v3.12.0)

### ISSUE THREAD

**Issue by ManuelBauer** [matomo-org/docker#180]
The latest Matomo version 3.12 is not published to [Docker Hub](https://hub.docker.com/_/matomo). When will be the version pushed to the Registry?

![Screenshot 2019-10-30 at 16 05 34](https://user-images.githubusercontent.com/1709215/67870450-29830d80-fb2f-11e9-89b9-15bc9abd1e37.png)

**Comment by dbrgn** [comment]
I thought that maybe the image only updates every weeks, but now it has been 9 days since the last update for `latest`.

Is there some misconfiguration / build failure? Anything we can help with? Unfortunately I'm not familiar how the build process for official docker images works...

**Comment by diesl** [comment]
@tianon Could you please update Matomo to the latest version? Thanks!

**Comment by tianon** [comment]
Sure, I've opened https://github.com/docker-library/official-images/pull/6906.

https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what is likely a useful reference here too.  I'm not officially a maintainer of the `matomo` image -- I just help out with it sometimes.  (Ideally one of the image maintainers would be making the PRs to https://github.com/docker-library/official-images instead of me.)

**Comment by diesl** [comment]
@tianon Thanks for the PR and also these helpful links!

@J0WI: Do you know which maintainer would be the best recipient for this information?

**Comment by J0WI** [comment]
> Do you know which maintainer would be the best recipient for this information?

That's probably me, because nobody else was active in this repo this year :no_mouth:
Thanks @tianon for helping out!
