### ISSUE TITLE
Alpine Variant - Apache/FPM

### ISSUE THREAD

**Issue by Silvenga** [matomo-org/docker#91]
Let's start a discussion on how we want to handle the Alpine variant of Matomo.

Goals:
- [ ] Alpine Apache
  - Should only require a link to MySQL
  - Should allow a link to Redis
- [x] Alpine FPM
  - Would require a reverse proxy server to handle HTTP requests.

I know that #82 exists already - @crazy-max do you have any input?

**Comment by Silvenga** [comment]
Oh, I forgot about redis and we should definitely have docker-compose examples.

Do you think #82 can be used as a base for fpm-alpine?

**Comment by crazy-max** [comment]
Apart from the copy/paste error [here](https://github.com/matomo-org/docker/pull/82/files#diff-e7264ad027b5ed7bd77fabce9955416fR48), that sounds good. 

I'm not used to using the PHP basic image and I don't like it too much because this one uses (for the fpm-alpine part for example) a rather [old version of Alpine (alpine:3.4)](https://github.com/docker-library/php/blob/master/7.1/alpine3.4/fpm/Dockerfile#L7) which dates from 2016 and embeds many CVE.

From my point of view, it should have both maintainability ease but also be on the latest stable versions of the base OS. This is the case with [my Matomo image](https://github.com/crazy-max/docker-matomo/blob/master/Dockerfile) which uses Alpine version 3.7 for example.

**Comment by J0WI** [comment]
Thanks for the hint, I fixed the virtual package name in https://github.com/matomo-org/docker/pull/82/commits/1cf05768fc281ffc3e29b9e827183c2bff56aed9.

The OS version issue is already addressed upstream (#504).

**Comment by J0WI** [comment]
I just rebased #82 on top of current master. So it's ready for a review again.

**Comment by J0WI** [comment]
Alpine FPM has been added in #82

**Comment by crazy-max** [comment]
Thanks @J0WI !

**Comment by J0WI** [comment]
Nope, no new version has been published so far.

**Comment by J0WI** [comment]
Release has been made: https://github.com/docker-library/official-images/commit/0360fecd720eaf74ca53ba05dc7d4d35096730b8

**Comment by J0WI** [comment]
Do we really need an apache variant based on Alpine?
I don't think so. Feel free to (re-)open an issue with some arguments for it.
